id: eb6b6dad9b7a4b71b2f188bec7f33365
initial_creation_type: ocr
source_metadata:
  volumes:
    b7e4ac5347444561b8d7fbc17498b988:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: དེ་ཁོ་ན་ཉིད་ཕྱག་རྒྱ་ཆེན་པོ་ཡི་གེ་མེད་པའི་མན་ངག།
      total_pages: 1902
      volume_number: 26
